package net.huray.sdk.model

data class AtfleeWeightData(
    val bmi: Double,
    val bmr: Int,
    val bodyFatPercent: Double,
    val boneMass: Double,
    val fatFreeMass: Double,
    val moistureMass: Double,
    val moisturePercent: Double,
    val muscleMass: Double,
    val musclePercent: Double,
    val minerals: Double,
    val physicalAge: Double,
    val proteinPercent: Double,
    val proteinMass: Double,
    val skeletalMuscleMass: Double,
    val skeletalMusclePercent: Double,
    val subcutaneousFatPercent: Double,
    val visceralFat: Double,
    val waistHipRatio: Double,
    val weightKg: Double,
    val extraData: AtfleeExtraWeightData? = null,
)

data class AtfleeExtraWeightData(
    val leftArm: Double,
    val rightArm: Double,
    val leftLeg: Double,
    val rightLeg: Double,
    val allBody: Double,
    val leftArmKg: Double,
    val rightArmKg: Double,
    val leftLegKg: Double,
    val rightLegKg: Double,
    val allBodyKg: Double,
    val leftArmMuscle: Double,
    val rightArmMuscle: Double,
    val leftLegMuscle: Double,
    val rightLegMuscle: Double,
    val allBodyMuscle: Double,
    val leftArmMuscleKg: Double,
    val rightArmMuscleKg: Double,
    val leftLegMuscleKg: Double,
    val rightLegMuscleKg: Double,
    val allBodyMuscleKg: Double,
)